[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_token_fetch_program = "GepFD6mcEKFAHvsm5VrYoNtFjh7niECpxu4tSnzxdvQu"

[programs.testnet]
solana_token_fetch_program = "GepFD6mcEKFAHvsm5VrYoNtFjh7niECpxu4tSnzxdvQu"

[programs.mainnet]
solana_token_fetch_program = "GepFD6mcEKFAHvsm5VrYoNtFjh7niECpxu4tSnzxdvQu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
